import dotenv from 'dotenv'
dotenv.config();

export const ENV ={
    NODE_ENV:process.env.NODE_ENV,
    PORT:process.env.PORT,
    DB_URL:process.env.DB_URL,
    CLERK_PUBLISHABLE_KEY:process.CLERK_PUBLISHABLE_KEY,
    CLERK_SECRET_KEY:process.CLERK_SECRET_KEY,
    CLOUDINARY_API_KEY:process.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET:process.CLOUDINARY_API_SECRET,
    CLOUDINARY_CLOUD_NAME:process.CLOUDINARY_CLOUD_NAME,
    INNGEST_SIGNING_KEY:process.INNGEST_SIGNING_KEY,
}